apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-secret
  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: secret-exemple
    creationPolicy: Owner
  data:
    - secretKey: secret-exemple
      remoteRef:
        key: kv/example
        property: secret-exemple
